//! Feature registry — all Velocity feature modules.
//! Generated by tools/generate_feature_registry.py from feature_catalog.json.
//! Do not edit this file directly or spawn processes here.

const std = @import("std");
const activation_policy = @import("activation_policy.zig");

pub const Mode = enum { core, dev, heavy, agent, remote, legacy };
pub const Status = enum { stub, prototype, working, optimized };

pub const FeatureEntry = struct {
    id: []const u8,
    name: []const u8,
    mode: Mode,
    default_enabled: bool,
    startup_allowed: bool,
    memory_budget_mb: u32,
    max_processes: u32,
    status: Status = .stub,
    enabled: bool = false,
    loaded: bool = false,
    activation_ms: u32 = 0,
    process_count: u32 = 0,
    activation_reason: []const u8 = "none",
};

pub const startup_critical_count: u32 = 11;

pub const catalog = [_]FeatureEntry{
    .{ .id = "feature.activity-rail", .name = "Activity Rail", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.sidebar", .name = "Sidebar", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 4, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.panel", .name = "Panel", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 4, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.status-bar", .name = "Status Bar", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 2, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.command-palette", .name = "Command Palette", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 4, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.quick-open", .name = "Quick Open", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.editor-groups", .name = "Editor Groups", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.tabs", .name = "Tabs", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 4, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.breadcrumbs", .name = "Breadcrumbs", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.layout", .name = "Layout", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.settings", .name = "Settings", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.keybindings", .name = "Keybindings", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.themes", .name = "Themes", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 2, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.notifications", .name = "Notifications", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.context-menus", .name = "Context Menus", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.hover", .name = "Hover", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.dialogs", .name = "Dialogs", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.welcome-empty-state", .name = "Welcome / Empty State", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.accessibility-core", .name = "Accessibility Core", .mode = .core, .default_enabled = true, .startup_allowed = true, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.file-explorer", .name = "File Explorer", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.workspace-manager", .name = "Workspace Manager", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.multi-root-workspaces", .name = "Multi-root Workspaces", .mode = .dev, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.recent-projects", .name = "Recent Projects", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.file-watchers", .name = "File Watchers", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.hot-exit", .name = "Hot Exit", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.auto-save", .name = "Auto Save", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.backups", .name = "Backups", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.file-encoding", .name = "File Encoding", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.file-decorations", .name = "File Decorations", .mode = .dev, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.drag-drop", .name = "Drag and Drop", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.dirty-state", .name = "Dirty State", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.compare-files", .name = "Compare Files", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.diff-editor", .name = "Diff Editor", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.merge-editor", .name = "Merge Editor", .mode = .dev, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 24, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.editor-island", .name = "Editor Island", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.monaco-bridge", .name = "Monaco Bridge", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 80, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.native-editor-research", .name = "Native Editor Research", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 0, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.multi-cursor", .name = "Multi Cursor", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.column-selection", .name = "Column Selection", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.find-replace", .name = "Find Replace", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.search-selection", .name = "Search Selection", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.snippets", .name = "Snippets", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.syntax-highlighting", .name = "Syntax Highlighting", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.semantic-tokens", .name = "Semantic Tokens", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.bracket-matching", .name = "Bracket Matching", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.bracket-pair-colorization", .name = "Bracket Pair Colorization", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.folding", .name = "Folding", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.minimap", .name = "Minimap", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.code-lens", .name = "Code Lens", .mode = .dev, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.inlay-hints", .name = "Inlay Hints", .mode = .dev, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.inline-suggestions", .name = "Inline Suggestions", .mode = .agent, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.hover-docs", .name = "Hover Docs", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.go-to-definition", .name = "Go to Definition", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.go-to-references", .name = "Go to References", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.peek", .name = "Peek", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.rename-symbol", .name = "Rename Symbol", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.code-actions", .name = "Code Actions", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.refactor", .name = "Refactor", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.formatting", .name = "Formatting", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.outline", .name = "Outline", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.symbols", .name = "Symbols", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.problems", .name = "Problems", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.diagnostics", .name = "Diagnostics", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.language-status", .name = "Language Status", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.workspace-search", .name = "Workspace Search", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 24, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.quick-search", .name = "Quick Search", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.search-results", .name = "Search Results", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.search-replace", .name = "Search Replace", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.ripgrep-adapter", .name = "Ripgrep Adapter", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 1, .status = .working, .enabled = true },
    .{ .id = "feature.search-index", .name = "Search Index", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 64, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.search-editor", .name = "Search Editor", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.fuzzy-file-search", .name = "Fuzzy File Search", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.symbol-search", .name = "Symbol Search", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.command-search", .name = "Command Search", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.terminal", .name = "Terminal", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 1, .status = .prototype, .enabled = true },
    .{ .id = "feature.terminal-profiles", .name = "Terminal Profiles", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.terminal-tabs", .name = "Terminal Tabs", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.terminal-splits", .name = "Terminal Splits", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.terminal-links", .name = "Terminal Links", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.terminal-shell-integration", .name = "Terminal Shell Integration", .mode = .dev, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.terminal-find", .name = "Terminal Find", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.task-runner", .name = "Task Runner", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 1, .status = .working, .enabled = true },
    .{ .id = "feature.task-detector", .name = "Task Detector", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.problem-matchers", .name = "Problem Matchers", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.output-panel", .name = "Output Panel", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.scm-core", .name = "SCM Core", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.git-provider", .name = "Git Provider", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 24, .max_processes = 1, .status = .prototype, .enabled = true },
    .{ .id = "feature.git-status", .name = "Git Status", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 1, .status = .working, .enabled = true },
    .{ .id = "feature.git-diff", .name = "Git Diff", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 1, .status = .working, .enabled = true },
    .{ .id = "feature.git-stage-commit", .name = "Git Stage/Commit", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 1, .status = .working, .enabled = true },
    .{ .id = "feature.git-branches", .name = "Git Branches", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 1, .status = .working, .enabled = true },
    .{ .id = "feature.git-merge-conflicts", .name = "Git Merge Conflicts", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.git-history", .name = "Git History", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 1, .status = .stub, .enabled = false },
    .{ .id = "feature.pull-request-provider", .name = "Pull Request Provider", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 24, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.source-control-provider-api", .name = "SCM Provider API", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.debug-core", .name = "Debug Core", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 24, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.debug-adapter-protocol", .name = "Debug Adapter Protocol", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.debug-configurations", .name = "Debug Configurations", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.breakpoints", .name = "Breakpoints", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.call-stack", .name = "Call Stack", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.variables", .name = "Variables", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.watch", .name = "Watch", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.debug-console", .name = "Debug Console", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.debug-repl", .name = "Debug REPL", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.test-core", .name = "Test Core", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.test-discovery", .name = "Test Discovery", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 1, .status = .prototype, .enabled = true },
    .{ .id = "feature.test-explorer", .name = "Test Explorer", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.test-output", .name = "Test Output", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .working, .enabled = true },
    .{ .id = "feature.coverage", .name = "Coverage", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 1, .status = .stub, .enabled = false },
    .{ .id = "feature.lsp-broker", .name = "LSP Broker", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.lsp-process-manager", .name = "LSP Process Manager", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 4, .status = .prototype, .enabled = true },
    .{ .id = "feature.language-registry", .name = "Language Registry", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.language-server-registry", .name = "Language Server Registry", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.language-client", .name = "Language Client", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.formatter-registry", .name = "Formatter Registry", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.diagnostic-registry", .name = "Diagnostic Registry", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.completion-registry", .name = "Completion Registry", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.semantic-token-registry", .name = "Semantic Token Registry", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.js-ts-language-pack", .name = "JS/TS Language Pack", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 48, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.json-language-pack", .name = "JSON Language Pack", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.css-html-language-pack", .name = "CSS/HTML Language Pack", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 24, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.markdown-language-pack", .name = "Markdown Language Pack", .mode = .dev, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.python-language-pack", .name = "Python Language Pack", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 64, .max_processes = 1, .status = .stub, .enabled = false },
    .{ .id = "feature.rust-language-pack", .name = "Rust Language Pack", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 64, .max_processes = 1, .status = .stub, .enabled = false },
    .{ .id = "feature.go-language-pack", .name = "Go Language Pack", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 48, .max_processes = 1, .status = .stub, .enabled = false },
    .{ .id = "feature.native-plugin-runtime", .name = "Native Plugin Runtime", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-manifest", .name = "Plugin Manifest", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-permissions", .name = "Plugin Permissions", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-activation", .name = "Plugin Activation", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-sandbox", .name = "Plugin Sandbox", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-registry-client", .name = "Plugin Registry Client", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-install", .name = "Plugin Install", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-update", .name = "Plugin Update", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-signatures", .name = "Plugin Signatures", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-scorecard", .name = "Plugin Scorecard", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-marketplace-ui", .name = "Plugin Marketplace UI", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-devtools", .name = "Plugin Devtools", .mode = .dev, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.plugin-host-process", .name = "Plugin Host Process", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 1, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-memory-budget", .name = "Plugin Memory Budget", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.legacy-vsix-bridge", .name = "Legacy VSIX Bridge", .mode = .legacy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 64, .max_processes = 1, .status = .stub, .enabled = false },
    .{ .id = "feature.legacy-extension-host", .name = "Legacy Extension Host", .mode = .legacy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 128, .max_processes = 1, .status = .stub, .enabled = false },
    .{ .id = "feature.agent-composer", .name = "Agent Composer", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 24, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.inline-agent-edit", .name = "Inline Agent Edit", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-task-list", .name = "Agent Task List", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-review", .name = "Agent Review", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-apply", .name = "Agent Apply", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-checkpoints", .name = "Agent Checkpoints", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-context", .name = "Agent Context", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 24, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-indexer", .name = "Agent Indexer", .mode = .agent, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 64, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.agent-memory", .name = "Agent Memory", .mode = .agent, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.agent-permissions", .name = "Agent Permissions", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-terminal-approval", .name = "Agent Terminal Approval", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-tool-registry", .name = "Agent Tool Registry", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-model-router", .name = "Agent Model Router", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-local-adapter", .name = "Agent Local Adapter", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-cloud-adapter", .name = "Agent Cloud Adapter", .mode = .agent, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.agent-mcp-adapter", .name = "Agent MCP Adapter", .mode = .agent, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.agent-hooks", .name = "Agent Hooks", .mode = .agent, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.notebooks", .name = "Notebooks", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 64, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.notebook-renderers", .name = "Notebook Renderers", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.markdown-preview", .name = "Markdown Preview", .mode = .dev, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 24, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.webviews", .name = "Webviews", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 48, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.custom-editors", .name = "Custom Editors", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 48, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.timeline", .name = "Timeline", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.local-history", .name = "Local History", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.profiles", .name = "Profiles", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.settings-sync", .name = "Settings Sync", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.remote-ssh", .name = "Remote SSH", .mode = .remote, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.remote-containers", .name = "Remote Containers", .mode = .remote, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 48, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.remote-tunnels", .name = "Remote Tunnels", .mode = .remote, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 24, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.port-forwarding", .name = "Port Forwarding", .mode = .remote, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.integrated-browser", .name = "Integrated Browser", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 64, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.accessibility-signals", .name = "Accessibility Signals", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.voice", .name = "Voice", .mode = .heavy, .default_enabled = false, .startup_allowed = false, .memory_budget_mb = 32, .max_processes = 0, .status = .stub, .enabled = false },
    .{ .id = "feature.performance-hud", .name = "Performance HUD", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .prototype, .enabled = true },
    .{ .id = "feature.process-governor-ui", .name = "Process Governor UI", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.terminal-memory-inspector", .name = "Terminal Memory Inspector", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-permission-inspector", .name = "Plugin Permission Inspector", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.plugin-performance-score", .name = "Plugin Performance Score", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.workspace-trust-plus", .name = "Workspace Trust Plus", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.workspace-process-sandbox", .name = "Workspace Process Sandbox", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.crash-leak-reporter", .name = "Crash/Leak Reporter", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.feature-toggle-matrix", .name = "Feature Toggle Matrix", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.startup-flamegraph", .name = "Startup Flamegraph View", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.ram-budget-dashboard", .name = "RAM Budget Dashboard", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 4, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.project-capsule", .name = "Project Capsule", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-autonomy-slider", .name = "Agent Autonomy Slider", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.agent-worktree-manager", .name = "Agent Worktree Manager", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.parallel-agent-task-board", .name = "Parallel Agent Task Board", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 16, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.codebase-index-health", .name = "Codebase Index Health View", .mode = .agent, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.command-journal", .name = "Command Journal", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 8, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.instant-safe-mode", .name = "Instant Safe Mode", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.no-extensions-mode", .name = "No-Extensions Mode", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.no-agents-mode", .name = "No-Agents Mode", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.minimal-battery-mode", .name = "Minimal Battery Mode", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.memory-pressure-mode", .name = "Memory Pressure Mode", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.kill-all-workspace-processes", .name = "Kill All Workspace Processes", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.freeze-background-terminals", .name = "Freeze Background Terminals", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.suspend-inactive-language-servers", .name = "Suspend Inactive Language Servers", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
    .{ .id = "feature.disable-heavy-features", .name = "Disable Heavy Features", .mode = .core, .default_enabled = true, .startup_allowed = false, .memory_budget_mb = 2, .max_processes = 0, .status = .stub, .enabled = true },
};

pub const registered_count: u32 = @intCast(catalog.len);

pub fn countEnabled(entries: []const FeatureEntry) u32 {
    var n: u32 = 0;
    for (entries) |e| if (e.enabled) {
        n += 1;
    };
    return n;
}

pub fn countLoaded(entries: []const FeatureEntry) u32 {
    var n: u32 = 0;
    for (entries) |e| if (e.loaded) {
        n += 1;
    };
    return n;
}

pub fn assertNoStartupNonCritical(entries: []const FeatureEntry) bool {
    for (entries) |e| {
        if (e.loaded and !e.startup_allowed) return false;
    }
    return true;
}

test "catalog size" {
    try std.testing.expectEqual(@as(usize, registered_count), catalog.len);
}

test "startup critical subset is small" {
    var n: u32 = 0;
    for (catalog) |e| if (e.startup_allowed) {
        n += 1;
    };
    try std.testing.expect(n == startup_critical_count);
    try std.testing.expect(n < 30);
}
