#!/usr/bin/env python3
"""Generate the Zig feature registry from the canonical JSON catalog."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import NoReturn

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "apps/native-shell/src/core/feature_catalog.json"
OUTPUT_PATH = ROOT / "apps/native-shell/src/core/feature_registry.zig"

EXPECTED_FEATURES = 200
MODES = frozenset({"core", "dev", "heavy", "agent", "remote", "legacy"})
STATUSES = frozenset({"stub", "prototype", "working", "optimized"})
U32_MAX = (1 << 32) - 1


def fail(message: str) -> NoReturn:
    raise ValueError(message)


def require_string(entry: object, key: str, index: int) -> str:
    if not isinstance(entry, dict):
        fail(f"feature {index}: expected an object")
    value = entry.get(key)
    if not isinstance(value, str) or not value:
        fail(f"feature {index}: {key} must be a non-empty string")
    return value


def require_bool(entry: dict[str, object], key: str, feature_id: str) -> bool:
    value = entry.get(key)
    if not isinstance(value, bool):
        fail(f"{feature_id}: {key} must be a boolean")
    return value


def require_u32(entry: dict[str, object], key: str, feature_id: str) -> int:
    value = entry.get(key)
    if isinstance(value, bool) or not isinstance(value, int):
        fail(f"{feature_id}: {key} must be an integer")
    if not 0 <= value <= U32_MAX:
        fail(f"{feature_id}: {key} must be between 0 and {U32_MAX}")
    return value


def zig_string(value: str) -> str:
    escaped: list[str] = ['"']
    for char in value:
        codepoint = ord(char)
        if char == '"':
            escaped.append(r"\"")
        elif char == "\\":
            escaped.append(r"\\")
        elif char == "\n":
            escaped.append(r"\n")
        elif char == "\r":
            escaped.append(r"\r")
        elif char == "\t":
            escaped.append(r"\t")
        elif codepoint < 0x20 or codepoint == 0x7F:
            escaped.append(f"\\x{codepoint:02x}")
        else:
            escaped.append(char)
    escaped.append('"')
    return "".join(escaped)


def load_features() -> list[dict[str, object]]:
    raw = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    if not isinstance(raw, list):
        fail("catalog root must be an array")
    if len(raw) != EXPECTED_FEATURES:
        fail(f"catalog must contain exactly {EXPECTED_FEATURES} features, found {len(raw)}")

    features: list[dict[str, object]] = []
    seen_ids: set[str] = set()
    for index, raw_entry in enumerate(raw):
        if not isinstance(raw_entry, dict):
            fail(f"feature {index}: expected an object")
        entry: dict[str, object] = raw_entry
        feature_id = require_string(entry, "id", index)
        if not feature_id.startswith("feature."):
            fail(f"{feature_id}: id must start with 'feature.'")
        if feature_id in seen_ids:
            fail(f"duplicate feature id: {feature_id}")
        seen_ids.add(feature_id)

        require_string(entry, "name", index)
        mode = require_string(entry, "mode", index)
        if mode not in MODES:
            fail(f"{feature_id}: invalid mode {mode!r}")
        status = require_string(entry, "status", index)
        if status not in STATUSES:
            fail(f"{feature_id}: invalid status {status!r}")
        require_bool(entry, "defaultEnabled", feature_id)
        require_bool(entry, "startupAllowed", feature_id)
        require_u32(entry, "memoryBudgetMB", feature_id)

        process_budget = entry.get("processBudget")
        if not isinstance(process_budget, dict):
            fail(f"{feature_id}: processBudget must be an object")
        require_u32(process_budget, "maxProcesses", feature_id)
        features.append(entry)
    return features


def render(features: list[dict[str, object]]) -> str:
    startup_critical_count = sum(
        1 for entry in features if entry["startupAllowed"] is True
    )
    if startup_critical_count > U32_MAX:
        fail("startup critical count exceeds u32")

    lines = [
        "//! Feature registry — all Velocity feature modules.",
        "//! Generated by tools/generate_feature_registry.py from feature_catalog.json.",
        "//! Do not edit this file directly or spawn processes here.",
        "",
        'const std = @import("std");',
        'const activation_policy = @import("activation_policy.zig");',
        "",
        "pub const Mode = enum { core, dev, heavy, agent, remote, legacy };",
        "pub const Status = enum { stub, prototype, working, optimized };",
        "",
        "pub const FeatureEntry = struct {",
        "    id: []const u8,",
        "    name: []const u8,",
        "    mode: Mode,",
        "    default_enabled: bool,",
        "    startup_allowed: bool,",
        "    memory_budget_mb: u32,",
        "    max_processes: u32,",
        "    status: Status = .stub,",
        "    enabled: bool = false,",
        "    loaded: bool = false,",
        "    activation_ms: u32 = 0,",
        "    process_count: u32 = 0,",
        '    activation_reason: []const u8 = "none",',
        "};",
        "",
        f"pub const startup_critical_count: u32 = {startup_critical_count};",
        "",
        "pub const catalog = [_]FeatureEntry{",
    ]

    for entry in features:
        process_budget = entry["processBudget"]
        assert isinstance(process_budget, dict)
        enabled = "true" if entry["defaultEnabled"] else "false"
        startup_allowed = "true" if entry["startupAllowed"] else "false"
        lines.append(
            "    .{ "
            f".id = {zig_string(str(entry['id']))}, "
            f".name = {zig_string(str(entry['name']))}, "
            f".mode = .{entry['mode']}, "
            f".default_enabled = {enabled}, "
            f".startup_allowed = {startup_allowed}, "
            f".memory_budget_mb = {entry['memoryBudgetMB']}, "
            f".max_processes = {process_budget['maxProcesses']}, "
            f".status = .{entry['status']}, "
            f".enabled = {enabled} "
            "},"
        )

    lines.extend(
        [
            "};",
            "",
            "pub const registered_count: u32 = @intCast(catalog.len);",
            "",
            "pub fn countEnabled(entries: []const FeatureEntry) u32 {",
            "    var n: u32 = 0;",
            "    for (entries) |e| if (e.enabled) {",
            "        n += 1;",
            "    };",
            "    return n;",
            "}",
            "",
            "pub fn countLoaded(entries: []const FeatureEntry) u32 {",
            "    var n: u32 = 0;",
            "    for (entries) |e| if (e.loaded) {",
            "        n += 1;",
            "    };",
            "    return n;",
            "}",
            "",
            "pub fn assertNoStartupNonCritical(entries: []const FeatureEntry) bool {",
            "    for (entries) |e| {",
            "        if (e.loaded and !e.startup_allowed) return false;",
            "    }",
            "    return true;",
            "}",
            "",
            'test "catalog size" {',
            "    try std.testing.expectEqual(@as(usize, registered_count), catalog.len);",
            "}",
            "",
            'test "startup critical subset is small" {',
            "    var n: u32 = 0;",
            "    for (catalog) |e| if (e.startup_allowed) {",
            "        n += 1;",
            "    };",
            "    try std.testing.expect(n == startup_critical_count);",
            "    try std.testing.expect(n < 30);",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit nonzero when the generated registry differs from the checked-in file",
    )
    args = parser.parse_args()

    try:
        generated = render(load_features())
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"feature registry generation failed: {error}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = OUTPUT_PATH.read_text(encoding="utf-8")
        except OSError as error:
            print(f"feature registry check failed: {error}", file=sys.stderr)
            return 1
        if current != generated:
            print(
                f"{OUTPUT_PATH.relative_to(ROOT)} is out of date; "
                "run npm run features:generate",
                file=sys.stderr,
            )
            return 1
        print("feature registry is up to date")
        return 0

    OUTPUT_PATH.write_text(generated, encoding="utf-8", newline="\n")
    print(f"generated {OUTPUT_PATH.relative_to(ROOT)} ({EXPECTED_FEATURES} features)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
